{% set name = "onnx-tf" %}
{% set version = "1.0" %}
{% set sha256 = "34054adeb61de97bc596b8008f5a78abbd9c3b5da69ecaf9c4b075d01ed20dca" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # Could be noarch: python except for the tests....
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: true  # [win32 or (win64 and py27)]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - onnx
    - tensorflow

test:
  imports:
    # onnx_tf.__init__ is empty, doesn't actually do anything.
    - onnx_tf
    # These require importing tensorflow, which currently the Linux CI can't do.
    - onnx_tf.backend      # [not linux]
    - onnx_tf.backend_rep  # [not linux]

about:
  home: http://github.com/onnx/onnx-tensorflow
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'  # https://github.com/onnx/onnx-tensorflow/pull/14
  summary: 'Experimental Tensorflow Backend for ONNX'
  doc_url: https://github.com/onnx/onnx-tensorflow
  dev_url: https://github.com/onnx/onnx-tensorflow

extra:
  recipe-maintainers:
    - dougalsutherland
