{% set name = "onnx-tf" %}
{% set version = "1.1" %}
{% set sha256 = "37a97cdcff5d432495a6a463f2e81172897ee6c3509b100f581b99700d3aa4c9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # Could be noarch: python except for the tests....
  number: 0
  script: python -m pip install --ignore-installed --no-deps .
  skip: true  # [win32 or (win64 and py27)]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - onnx
    - tensorflow

test:
  imports:
    # Requires importing tensorflow, which currently the Linux CI can't do.
    - onnx_tf  # [not linux]

about:
  home: http://github.com/onnx/onnx-tensorflow
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Experimental Tensorflow Backend for ONNX'
  doc_url: https://github.com/onnx/onnx-tensorflow
  dev_url: https://github.com/onnx/onnx-tensorflow

extra:
  recipe-maintainers:
    - dougalsutherland
