# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "qeUHiF7siEiKPH6vLFMlOqoCn2MC+4W0nsJ6A7Z9FV1u9nIdklsjvKIcPUbyjNCy8cEhnz+irKn9GFIXHt1mZDPMzf/VIT2rPrq93PfqXCTKXALhaUf3Z3YymHl1Tt6OWR3irS8HfPRNNpKkQqILC/iZQlu1j6ees884YelNikxyARX4GyqOFBqabKbiKSBJv9A0PvKOar1h3AwcIdy/D+dlv3A9Tlpjw52CmiarDwaD+IjdmQTX7q0BPtBqvtaskiYQA9hBGOgiOETrrE/I89jmPaYBB7Wma94xNnJ01IXrs0CmFedG255FboQoGDhhm09tOKGPA5M4qEtmTaNHyshp44+91EiHXI3gfumL6Kl6OXm5S4+mT35FjJ/mCtYoPzeViPxCBXB122H/wr81/huA35GyncZu6cFol+vbQb1PQ0lqxkvRukf9azHcGQfSFIaQOfoOnfCbZkdi26dH29A11Y9vavsGKmO7/Hn/Q5z1rGYqX+/p31gIcHQw7XZJnNtv6fa7k0VW0rKSCzBT4FBDWOIhbV7zML/BaKdbC+c2mrP9CJLeEIwMm8HW4gOjgM6gC9sBI+ZWjRfubt5Nb9dZyLeYfyWx7WcyRs5CqRxBfnE+BPEmtDocbfymSoox05oTGEGe3yJtXsLdmJbcL+XEgQIcqVwJHYZCQTcTS+A="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
