travis:
  secure:
    BINSTAR_TOKEN: dwVazTF28jatPOdtWemO9kxH4hHqUZyPqo9CvQQX99+EfV2PhUyCQKTSKf0nadDsfI9ehLPAMl/pu12l58wKHbLJ8GEPJANzEqeEd9oPG8/jcDhQoatH4xrbuStKQndzr1F6E5HsmbDgPelbbplHLXwvzexmOur0idyEJWwTQDb/LZhWRawq3jHMtV3nWlHYcFbCGamIWM+ladJmWp2K/8TqWDc52I/L3UHuZMg2DVSvhhI60XHzvL9amvQnUN+YOvFR7fGF04Nx4I9kAfiN3sleLVKDO7U3f7FjpFp0+P0mqTBkg91CY4U8cALqazxdHNF1ZDl1ohAv5DL+8ZDQEgtwg5+Yin5TjcpyMuza+qtLYHe96BDNNbJZer935N1YkAap3Mp14KASLOPQmcOrWi67j6DVQ/wlAU/scHl5DGcy38bf+WpZ4aoWOqDFiSlw+UFK6kIpsDFK6++pg0C/Azar6FLWaZrEsZcTEqTBzY/vnDXxCJ08W89803SQ6SajwKdGcXpl3kJaQb2TJpDhDMi4G8O7g3EIz2QgmNLW2n5zLAVFi5ivJ7U+PzVUzD48hBRQyUt2j3eaJFrSibmDqQCIpbJp4s2YkFBmO0Xdlso9+vj85LUClY0mjKG8P48PtuC21bIGVbbt34wyAxiA2j3nAMrKbs5eVhG86pJ50vM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
