travis:
  secure:
    BINSTAR_TOKEN: ZnAxXRzzeuT0pwKiElbUWMWWGH4CW/5W/O3QhruZ6xxXaqm6TljN9QyrLGZvGhsbKR7eRo0cHWgAIhlrdZTbvyrrqG13thJKByzuRj/G8YlSZLU4zmKUNh1gaRxl6Zo5rYLNmc/EaW4WIElkgvjhLrnANw5FAPTOtRgdgyZ2ZE7fwaUgh2dOoxT1kmy6oThgrGLTocTrUXjiri5zsMzPVEEPi80u6NwmW+/UiuEWxFgg5LAH7qavBxV2P/WH6OvHDq+I+tPHv/Q0amSvcq+kbV5nXS7OSiw1VoXY++eKUguLZvcBxgupn6yL+wPQxyeBR5RwoDKpPfFp5noTgfNCchUtjxlBScYZuW6lBAPI7tb636pto5z4/dj4j/YXdAzQjywIgV6xorgWEIaBLm3avq+yiS1cKrlZ6y4iipt/8wkGyq9/dfU+QqySHJrCmJScY15T7oduIghpgmHsSz6vieGpvZSlwe5XuoyjJwy1BE1rYA/S/4vuYaRMDAGrAWZlRhGJV+QcNBEoraS5C861BmH1bz1H8acyxoaHVxGje4jlHX629lxT1tQ5QQJKKbd2moAn57oUGDQIDJ5bRX/VKjRNgjHNDpQw/MvVZL/e5+W6XLS+J7JHunBBdbwIDP/01894t3SAyS5E3ZXZ8YV/tfJ0XTClqtCk2F1kEkPB5Io=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
