travis:
  secure:
    BINSTAR_TOKEN: qeUHiF7siEiKPH6vLFMlOqoCn2MC+4W0nsJ6A7Z9FV1u9nIdklsjvKIcPUbyjNCy8cEhnz+irKn9GFIXHt1mZDPMzf/VIT2rPrq93PfqXCTKXALhaUf3Z3YymHl1Tt6OWR3irS8HfPRNNpKkQqILC/iZQlu1j6ees884YelNikxyARX4GyqOFBqabKbiKSBJv9A0PvKOar1h3AwcIdy/D+dlv3A9Tlpjw52CmiarDwaD+IjdmQTX7q0BPtBqvtaskiYQA9hBGOgiOETrrE/I89jmPaYBB7Wma94xNnJ01IXrs0CmFedG255FboQoGDhhm09tOKGPA5M4qEtmTaNHyshp44+91EiHXI3gfumL6Kl6OXm5S4+mT35FjJ/mCtYoPzeViPxCBXB122H/wr81/huA35GyncZu6cFol+vbQb1PQ0lqxkvRukf9azHcGQfSFIaQOfoOnfCbZkdi26dH29A11Y9vavsGKmO7/Hn/Q5z1rGYqX+/p31gIcHQw7XZJnNtv6fa7k0VW0rKSCzBT4FBDWOIhbV7zML/BaKdbC+c2mrP9CJLeEIwMm8HW4gOjgM6gC9sBI+ZWjRfubt5Nb9dZyLeYfyWx7WcyRs5CqRxBfnE+BPEmtDocbfymSoox05oTGEGe3yJtXsLdmJbcL+XEgQIcqVwJHYZCQTcTS+A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
