travis:
  secure:
    BINSTAR_TOKEN: zC/P9IQyHmyfyB72iwWvaxi03csJFCDA9k84q0UeCCTlFpSfOHoUCUG93itO26t4LhquU7qPUykKStsCh+9mo0dGflHxQoOHhRhqdGWXl1p2mfvBDvdXi15MUNKCaYTQr10KC9BkUauzLwrYnbVdYdd17OTDVQCS5stPoYDjGwmMqOKVsEg96zJFAJ3BwttxSJgbn/8pftvJBl8JWcEbppKV2vSOQ09+T93eMpkom2kaxIk0fqZifyalOWZvaWj4LKObJE9DK9rLDxpDRLImJJWm+p5XA3ElhsoUMaGc2d400TJWPYEdjClMPjunH9PGl+0mwHD1eW+VftLUo8LwCfvfVkoAokSPtknp0yDWtp+D7rUhs0m1SNW1wuKCkP6gppgeQyGv4SFITpAiTeH+1n1W8dZhirSKDF1Gf/w3QkQVQD72pXmWaj8942oehJ/qxXFfLppINJSm2463hafriPsy551aY0+orQx4WJoEy6NLhOLiGllef25/SiQO85Trve6PTyS8v4WWXtHIfxQQw6zqqscC7RJe/PeSfvfFZb+fKgJVJ2Xm94hMyb1Yoic/cfHmxGqPUAeNugDOKFKRcfLYbwuju7euIajwNQAe/lYFmlsM5YvaIWynvCKV9tuqq9DEF6mFs315DIGeF4MneST42ZxY/iy9Dl33N8ZXnsw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
