travis:
  secure:
    BINSTAR_TOKEN: YKZKODxSThSoGW0Fdzh8aOyIQJRLaCtbjbOtOOrk50Oom13aaBciZI8yK+EZLVnGvHzI2VxwKVRf4xeZHHsoRaK6haWVZNKda0oXHgQdfZfNNaMIhx7QDXKr7OzeQnbrbP5lhPZLJ+xp6+r9irB5l+pidY/dQhA2/36FPW+g6pPEpUNFOvOITtaKKFh/4mCAKQsObdBvb6DWUTBs+XmxIB4nL+jrEWyjxJfDAB/WPlmyNqsCM0KM393MZwbokrT5FZOGLKOqC6uRQuF6ltvY3o0BzWmzgolf//le/MP3G4Zs+UDUn4VcTycrd7V5R1TaTvr6DrN8QlR69kB5GGK3BZMssAScIAydTpzmod+EjUDia3R5+e9H3LbHRTkMbQWY7f8+Kv5afWV6LIk3G6i0sZc5kUVo8drjkbOowOqhh5RDoNBXiIBFicKJmlvKH2yPncWKBNUrmwSWUaE5TFGlKCeVw1shYXmIi7rzH/PsxGQGcbH9MczHnIp8hTZ5hT/t3JEA23dhUy+OyczIU+SfOyjpjcAdZHbErafYhORljVNlxTKvLxQczzgtd3V7U7tF22QAfDi3FadGHHHOew87E3T8xYT5/XgSaopU7LM0i5glEvMXDiS3BGOSbdvYVzBC89zkdgrEN0zwRk7gi6anirv5iYasQNTlljEBrgwFUOY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
